apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
spec:
  clusterIP: None  # 关键点，必须是 None（用于 StatefulSet）
  selector:
    app.kubernetes.io/name: {{ .Values.redis.name }}
  ports:
    - port: {{ .Values.redis.port }}
      name: redis
      targetPort: {{ .Values.redis.port }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.redis.name }}
  serviceName: {{ .Values.redis.name }}
  replicas: {{ .Values.redis.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.redis.name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ .Values.redis.name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
              name: redis
