apiVersion: v1
kind: Service
metadata:
  name: my-nginx-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: my-nginx-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
